version: "3.9"

services:
  php-apache:
    container_name: php-apache
    build: .
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
volumes:
  wordpress_data: {}